language: python
cache: pip
sudo: required

# We are specifying the build matix manually, since there is too little overlap
# between the different builds:
jobs:
  include:
    - name: "Python 3.5 on Linux"
      python: "3.5"
      before_install:
        # This is required for XGBoost to work on older Ubuntu machines:
        - sudo apt-get update && sudo apt-get install libgomp1

    - name: "Python 3.6 on Linux"
      python: "3.6"
      before_install:
        # This is required for XGBoost to work on older Ubuntu machines:
        - sudo apt-get update && sudo apt-get install libgomp1

    - name: "Python 3.7 on Linux"
      python: "3.7"
      dist: xenial

    - name: "Python 3.6 on Windows"
      os: windows
      language: shell  # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip
        - git lfs pull
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - name: "Python 3.7 on Windows"
      os: windows
      language: shell  # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
        - python -m pip install --upgrade pip
        - git lfs pull
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Flake8"
      python: "3.6"
      git:
        lfs_skip_smudge: true
      install:
        - pip install flake8
      script:
        - flake8

  # Allow some newer versions of Python to fail for now
  # This will be changed once the required packages starts
  # supporting the newer versions of Python:
  fast_finish: true
  allow_failures:
    - name: "Flake8"
    - os: windows

# Command to install dependencies
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
script:
  - pytest --cov=starclass/
after_success:
  - codecov
branches:
  only:
    - master
    - devel
