language: python
python:
  - "3.5"
  - "3.6"
cache: pip

# Python 3.7 has to be done a different way
# https://github.com/travis-ci/travis-ci/issues/9069
jobs:
  include:
    - language: python
      python: "3.7"
      dist: xenial
      sudo: required

    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell  # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python --version
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell  # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4
        - python --version
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: "Flake8"
      python: "3.6"
      git:
        lfs_skip_smudge: true
      install:
        - pip install flake8
      script:
        - flake8

  # Allow some newer versions of Python to fail for now
  # This will be changed once the required packages starts
  # supporting the newer versions of Python:
  fast_finish: true
  allow_failures:
    - name: "Flake8"
    - os: windows

# Command to install dependencies
before_install:
  # This is required for XGBoost to work on older Ubuntu machines:
  - sudo apt-get update && sudo apt-get install libgomp1
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install codecov pytest-cov
script:
  - pytest --cov=starclass/
after_success:
  - codecov
branches:
  only:
    - master
    - devel
